baseURL = "https://snippets.hanamirb.org/"
title = "Hanami | Snippets"
copyright = "All rights reserved - 2018"
paginate = 5
languageCode = "en-us"
theme = "hanami"

pygmentscodefences = true
pygmentsstyle = "dracula"

[taxonomies]
   tag = "tags"
   category = "discover"

[permalinks]
  posts = "/:slug/"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  facebook = "hanamirb"
  twitter = "hanamirb"
  instagram = "hanamirb"
  github = "hanami/hanami"

  [params.icons]
    utils = "fa-cogs"
    validations = "fa-check-square-o"
    router = "fa-sitemap"
    controller = "fa-paper-plane"
    view = "fa-television"
    helpers = "fa-life-ring"
    mailer = "fa-envelope"
    cli = "fa-terminal"
    assets = "fa-folder-open-o"
    model = "fa-database"
    events = "fa-bullhorn"
    hanami = "fa-star"

  [params.colors]
    utils = "info"
    validations = "info"
    router = "fa-sitemap"
    controller = "primary"
    view = "primary"
    helpers = "info"
    mailer = "success"
    cli = "success"
    assets = "success"
    model = "primary"
    events = "success"
    hanami = "danger"
