baseURL = "https://snippets.hanamirb.org/"
title = "Hanami | Snippets"
copyright = "All rights reserved - 2018"
paginate = 5
languageCode = "en-us"
theme = "hanami"

pygmentscodefences = true
pygmentsstyle = "dracula"

[taxonomies]
   tag = "tags"
   category = "discover"

[permalinks]
  posts = "/:slug/"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  facebook = "hanamirb"
  twitter = "hanamirb"
  instagram = "hanamirb"
  github = "hanami/hanami"
