baseURL = "https://snippets.hanamirb.org/"
title = "Hanami Snippets"
copyright = "All rights reserved - 2018"
paginate = 5
languageCode = "en-us"
theme = "hanami"
googleAnalytics = "UA-47369640-2"

pygmentscodefences = true
pygmentsuseclasses = true

[outputs]
  home = ["HTML", "JSON"]

[taxonomies]
   tag = "tags"
   gem = "gems"
   version = "versions"

[permalinks]
  posts = "/:slug/"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  description = "Code snippets for Hanami Ruby web framework"
  facebook = "hanamirb"
  twitter = "hanamirb"
  instagram = "hanamirb"
  github = "hanami/hanami"
  keywords = "hanami,hanamirb,lotus,lotusrb,web,framework,ruby,open source,oss,os,software,free,free software,architecture,fast,lightweight,testing,tdd,bdd,test driven development,behaviour driven development,full stack,mvc,model view object,pattern,patterns,design patterns,oop,object oriented programming,testability,http,https,routing,router,http router,restful,resource,resources,convention,controller,models,repository,query,sql,interactors,two-step view,view,template,presenters,render,rendering,helpers,erb,haml,tilt,json,xml,yaml,yml,framwork,framewrok,riby,free sowftare"

  gems = [
   "hanami",
   "events",
   "model",
   "assets",
   "cli",
   "mailer",
   "helpers",
   "view",
   "controller",
   "router",
   "validations",
   "utils",
  ]

  [params.icons]
    utils = "fa-cogs"
    validations = "fa-check-square-o"
    router = "fa-sitemap"
    controller = "fa-paper-plane"
    view = "fa-television"
    helpers = "fa-life-ring"
    mailer = "fa-envelope"
    cli = "fa-terminal"
    assets = "fa-folder-open-o"
    model = "fa-database"
    events = "fa-bullhorn"
    hanami = "fa-star"
